##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-1-2020
##
##
name: Github Actions Token Sync

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Secrets
        uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            SNYK_TOKEN
            CIRCLECI_TOKEN
            GH_TOKEN_ADMIN
            GH_USER_ADMIN
            PAT_CLATOOL
            RP_ENDPOINT
            RP_UUID
            SNYK_TOKEN
            VT_API_KEY
          REPOSITORIES: |            
            splunk/splunk-dbx-add-on-for-*
            splunk/splunk-add-on-for-*
            splunk/dropbox-add-on-for-splunk
            splunk/dropbox-app-for-splunk
            splunk/seckit_sa_geolocation
            splunk/splunk-add-on-for-ucc-example
            splunk/splunk-add-on-for-ucc-example-ng
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
          CONCURRENCY: 2
          REPOSITORIES_LIST_REGEX: true
        env:
          CIRCLECI_TOKEN: ${{secrets.CIRCLECI_TOKEN}}
          GH_TOKEN_ADMIN: ${{secrets.GH_TOKEN_ADMIN}}
          GH_USER_ADMIN: ${{secrets.GH_USER_ADMIN}}
          PAT_CLATOOL: ${{secrets.PAT_CLATOOL}}
          RP_ENDPOINT: ${{secrets.RP_ENDPOINT}}
          RP_UUID: ${{secrets.RP_UUID}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
          VT_API_KEY: ${{secrets.VT_API_KEY}}
